import { createHash } from "node:crypto";
import { copyFile, readdir, readFile, writeFile } from "node:fs/promises";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const rootPath = fileURLToPath(new URL("../dist/", import.meta.url));
const noticeFiles = [
  "LICENSE",
  "NOTICE",
  "THIRD_PARTY_NOTICES.md",
  "THIRD_PARTY_LICENSES.txt",
];
for (const name of noticeFiles) {
  await copyFile(
    fileURLToPath(new URL(`../${name}`, import.meta.url)),
    join(rootPath, name),
  );
}
const files = [];
async function walk(directory) {
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) await walk(path);
    else if (
      entry.name !== "sw.js" &&
      (/\.(?:html|js|css|wasm|woff2?|svg|txt|md)$/.test(entry.name) ||
        entry.name === "LICENSE" ||
        entry.name === "NOTICE")
    ) {
      files.push(path);
    }
  }
}
await walk(rootPath);
files.sort();
const z3Version = createHash("sha256")
  .update(await readFile(join(rootPath, "z3/engine.js")))
  .digest("hex")
  .slice(0, 12);
const manifest = files.map((path) => {
  const url = `/${relative(rootPath, path).split(sep).join("/")}`;
  return url === "/z3/engine.js" || url === "/z3/worker-host.js"
    ? `${url}?v=${z3Version}`
    : url;
});
const digest = createHash("sha256");
digest.update(await readFile(fileURLToPath(import.meta.url)));
for (const path of files) digest.update(await readFile(path));
const version = digest.digest("hex").slice(0, 16);
const source = `/* Generated by scripts/build-offline.mjs. */
const CACHE = "clocktower-offline-${version}";
const PRECACHE = ${JSON.stringify(manifest)};
self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Avoid concurrent HTTP-cache writes when the first query also fetches WASM.
    // CacheStorage still retains these responses for offline use.
    await cache.addAll(PRECACHE.map((url) => new Request(url, { cache: "no-store" })));
    await self.skipWaiting();
  })());
});
self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith("clocktower-offline-") && key !== CACHE)
        await caches.delete(key);
    }
    await self.clients.claim();
  })());
});
self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET" || new URL(request.url).origin !== self.location.origin)
    return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    if (request.mode === "navigate") {
      try {
        const response = await fetch(request);
        if (response.ok) await cache.put("/index.html", response.clone());
        return response;
      } catch {
        return (await cache.match("/index.html")) ?? Response.error();
      }
    }
    const stored = await cache.match(request, { ignoreVary: true });
    if (stored) return stored;
    const response = await fetch(request);
    if (response.ok) await cache.put(request, response.clone());
    return response;
  })());
});
`;
await writeFile(join(rootPath, "sw.js"), source);
process.stdout.write(`Offline cache: ${manifest.length} files, ${version}\n`);
